### ISSUE TITLE
Run time errors

### ISSUE THREAD

**Issue by ssrb19** [Shen-Lab/cNMA#1]
Currently this gives the following error:
`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

This might be a python 3 vs 2.7 issue, but is rectifiable by changing line 2135 in ANMs.py to read:

`if Mnormed is None:`

instead of `if Mnormed == None:`

**Comment by hrch3n** [comment]
Thanks a lot for your feedback! I've fixed this issue and also did a couple of updates on the software. Please feel free to check the log and updated manual.
